version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
      - ollama

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    command: ollama start

volumes:
  mongo-data:
