version: '3.8'

services:
  frontend:
    build: ./frontend
    working_dir: /frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules  # Prevent overwriting installed modules
    depends_on:
      - backend


  backend:
    build: ./backend
    working_dir: /backend
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules  # Prevents overwriting node_modules
    environment:
      MONGO_URI: "mongodb://mongodb:27017/cv_database"
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  mongodb_data:
  ollama_data:
